[package]
name = "koharu"
version = "0.1.0"
description = "Manga translator"
edition = "2024"
license-file = "../LICENSE"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "koharu_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
tauri-plugin-persisted-scope = "2"
tauri-plugin-store = "2"
tokio = { version = "1.44.2", features = ["full"] }
anyhow = "1.0.98"
ort = "=2.0.0-rc.9"
image = "0.25.6"
tracing = { version = "0.1.41", features = ["log"] }
log = "0.4.27"
tauri-plugin-notification = "2"
tauri-plugin-fs = "2"
comic-text-detector = { path = "../comic-text-detector" }
manga-ocr = { path = "../manga-ocr" }
lama = { path = "../lama" }

[features]
cuda = ["ort/cuda"]
