[package]
name = "manga-ocr"
version.workspace = true
edition.workspace = true

[dependencies]
hf-hub = { workspace = true }
image = { workspace = true }
ort = { workspace = true }
anyhow = { workspace = true }
ndarray = { workspace = true }
clap = { workspace = true }
