[package]
name = "lama"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
hf-hub = "0.4.2"
image = "0.25.6"
ndarray = "0.16.1"
ort = "=2.0.0-rc.9"
