[package]
name = "lama"
version = "0.1.0"
edition = "2024"

[dependencies]
hf-hub = { workspace = true }
image = { workspace = true }
ort = { workspace = true }
anyhow = { workspace = true }
ndarray = { workspace = true }
clap = { workspace = true }
