[package]
name = "comic-text-detector"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.36", features = ["derive"] }
image = "0.25.6"
ndarray = "0.16.1"
ort = { version = "=2.0.0-rc.9", features = ["ndarray"] }
