name: Publish

on:
  push:
    tags:
      - 'v*.*.*'  # Matches version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to crates.io
        working-directory: ./src-tauri
        run: |
          cargo publish --token ${{ secrets.CARGO_TOKEN }} --all-features
